from sqlmodel import SQLModel
import uuid
from datetime import datetime
from typing import Optional
from pydantic import field_validator, EmailStr, Field

from .base import TunableBaseModel
from .validators import validate_password_strength, validate_username_format

# Schema per la REGISTRAZIONE
class UserCreate(TunableBaseModel):
    username: str
    email: EmailStr
    password: str

    @field_validator("password")
    def validate_password(cls, v: str) -> str:
        return validate_password_strength(v)

    @field_validator("username")
    def validate_username(cls, v: str) -> str:
        return validate_username_format(v)

    @field_validator("email", mode='before')
    def validate_email(cls, v: str) -> str:
        return v.lower()


# Schema for the data that get updated by the user from API
class UserUpdate(TunableBaseModel):
    username: Optional[str] = None
    email: Optional[EmailStr] = None
    password: Optional[str] = None
    rank_score: Optional[int] = None
    onboarding_completed: Optional[bool] = None
    timezone: Optional[str] = None
    bio: Optional[dict] = Field(default_factory=dict)


    @field_validator("password")
    def validate_password(cls, v: Optional[str]) -> Optional[str]:
        return validate_password_strength(v)

    @field_validator("username")
    def validate_username(cls, v: Optional[str]) -> Optional[str]:
        return validate_username_format(v)

    @field_validator("email", mode='before')
    def validate_email(cls, v: Optional[str]) -> Optional[str]:
        if v is None:
            return v
        return v.lower()


# Schema for talking to the db, the password is hashed and the id is generated by the db, so it is not required when creating a user
class UserUpdateDB(TunableBaseModel):
    username: Optional[str] = None
    email: Optional[EmailStr] = None
    hashed_password: Optional[str] = None
    rank_score: Optional[int] = None
    onboarding_completed: Optional[bool] = None
    timezone: Optional[str] = None
    bio: Optional[dict] = Field(default_factory=dict)

# Schema for the api response, this is what the user sees Eg: get request by the user, the password is not shown publicly
class UserPublic(SQLModel):
    id: uuid.UUID
    username: str
    email: str
    rank_score: int
    created_at: datetime
    onboarding_completed: bool
    timezone: str

    bio: Optional[dict] = Field(default_factory=dict)

# Schema per il TOKEN
class Token(SQLModel):
    access_token: str
    token_type: str = "bearer"
